table 'Результат запроса (2)'
	isHidden
	lineageTag: 13540611-b5d3-48df-98ba-edba9f7a2e61

	column Column1
		dataType: string
		isHidden
		lineageTag: 79c95fe5-164a-4547-b707-cb0acdfda787
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		isHidden
		lineageTag: 2c893add-36a6-4d61-a5f6-1118dc1fdedf
		summarizeBy: none
		sourceColumn: Column2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		isHidden
		lineageTag: e6cdcb5a-68b5-4777-8232-ea97052823a5
		summarizeBy: none
		sourceColumn: Column3

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		isHidden
		lineageTag: 767cc244-b527-4a7d-856e-b8b14e0867b3
		summarizeBy: none
		sourceColumn: Column4

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		isHidden
		lineageTag: 3c3c5942-46f4-464f-95fb-302bb342756b
		summarizeBy: none
		sourceColumn: Column5

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		isHidden
		lineageTag: faa11c24-b86f-4eec-ae39-c98695d024c0
		summarizeBy: none
		sourceColumn: Column6

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		isHidden
		lineageTag: 4392bcd8-109f-4633-b7ab-e0da026badaa
		summarizeBy: none
		sourceColumn: Column7

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		isHidden
		lineageTag: 3bde5cfa-b3f3-45db-ac38-3d216e11dc9c
		summarizeBy: none
		sourceColumn: Column8

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		isHidden
		lineageTag: c7864dbf-ae75-4f98-adc3-adc3ea82bd20
		summarizeBy: none
		sourceColumn: Column9

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		isHidden
		lineageTag: 87c0d0b6-d02d-4be5-8fbe-459f6882a09a
		summarizeBy: none
		sourceColumn: Column10

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		isHidden
		lineageTag: 0fd12abb-ba6b-4372-8bef-21e01ca4ef4d
		summarizeBy: none
		sourceColumn: Column11

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		isHidden
		lineageTag: bb1a8020-b41c-4200-b5d9-8aac92ff4068
		summarizeBy: none
		sourceColumn: Column12

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column13
		dataType: string
		isHidden
		lineageTag: 05e81cff-2cb7-496e-8492-a941eedc12e3
		summarizeBy: none
		sourceColumn: Column13

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column14
		dataType: string
		isHidden
		lineageTag: 541fab4a-4cd3-4b50-abce-f7183c76e6a6
		summarizeBy: none
		sourceColumn: Column14

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		isHidden
		lineageTag: 7a0068b7-677b-4229-a136-8d7576d41d2f
		summarizeBy: none
		sourceColumn: Column15

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column16
		dataType: string
		isHidden
		lineageTag: 4469dabd-d7cc-4f6d-a679-466eb0138e47
		summarizeBy: none
		sourceColumn: Column16

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column17
		dataType: string
		isHidden
		lineageTag: 4fca37db-593e-4af9-af4e-fda505698175
		summarizeBy: none
		sourceColumn: Column17

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column18
		dataType: string
		isHidden
		lineageTag: 94973678-6578-44b8-890e-fbb09214ebb5
		summarizeBy: none
		sourceColumn: Column18

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column19
		dataType: string
		isHidden
		lineageTag: 9fead5c0-e216-4ae1-8ab4-289e99300fb4
		summarizeBy: none
		sourceColumn: Column19

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Результат запроса (2)' = m
		mode: import
		source =
				let
				    Источник = Excel.Workbook(File.Contents("C:\Users\Slavic Asus\Downloads\query_result_2025-06-24T09_51_41.009478Z.xlsx"), null, true),
				    #"'Результат запроса$'_xlnm#_FilterDatabase1" = Источник{[Name="'Результат запроса$'_xlnm#_FilterDatabase"]}[Data],
				    #"Измененный тип" = Table.TransformColumnTypes(#"'Результат запроса$'_xlnm#_FilterDatabase1",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}})
				in
				    #"Измененный тип"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Навигация

