table '''Результат запроса$''_xlnm#_FilterDatabase'
	isHidden
	lineageTag: 7552b6f3-c3b8-4945-9d30-f900008bb3a5

	measure 'В среднем тратит пользователь' = 123
		formatString: 0
		lineageTag: 6849e92f-77c7-4c7b-96ab-42935887c2d8

	measure 'Количество активных пользователей' = DISTINCTCOUNT('public transaction'[user_id])
		formatString: 0
		lineageTag: 041be9b6-92dc-4ad1-bf74-e4e4e532e8e3

	column Column1
		dataType: string
		isHidden
		lineageTag: d1fab91f-03d1-49cf-91fd-b1493fcf2a3c
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		isHidden
		lineageTag: 61434b0d-b53d-411c-abdd-942c9adab0c8
		summarizeBy: none
		sourceColumn: Column2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		isHidden
		lineageTag: b632973b-a744-4ec2-b3fd-12fd1e9ed7d8
		summarizeBy: none
		sourceColumn: Column3

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		isHidden
		lineageTag: 276b6954-31ba-4a11-8dec-e9e5cb87c78b
		summarizeBy: none
		sourceColumn: Column4

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		isHidden
		lineageTag: 1695a9f6-f3c3-4c9f-8e58-9fbe764ba88b
		summarizeBy: none
		sourceColumn: Column5

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		isHidden
		lineageTag: 3a822a5c-b355-448a-88ad-719d79364e70
		summarizeBy: none
		sourceColumn: Column6

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		isHidden
		lineageTag: 7dd4a763-7cec-466c-a552-0731250a0de9
		summarizeBy: none
		sourceColumn: Column7

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		isHidden
		lineageTag: 497f2c1b-a140-48a4-9b2e-cc48bc57aaa2
		summarizeBy: none
		sourceColumn: Column8

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		isHidden
		lineageTag: 61118259-b006-4307-be86-f0e3a63d08d7
		summarizeBy: none
		sourceColumn: Column9

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		isHidden
		lineageTag: 393b77bc-3e79-4fa8-a929-71789e9e654a
		summarizeBy: none
		sourceColumn: Column10

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		isHidden
		lineageTag: 6a69aed8-315c-4af7-9a40-6fa90e4d25b3
		summarizeBy: none
		sourceColumn: Column11

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		isHidden
		lineageTag: d00c117a-6074-49d1-9a88-7a940bdc2498
		summarizeBy: none
		sourceColumn: Column12

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column13
		dataType: string
		isHidden
		lineageTag: c2b14bf0-03e5-4d0c-89b4-1394174096ff
		summarizeBy: none
		sourceColumn: Column13

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column14
		dataType: string
		isHidden
		lineageTag: 8d6ac166-0b96-495d-a31b-85819fd182b1
		summarizeBy: none
		sourceColumn: Column14

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		isHidden
		lineageTag: 18bf5d8a-872f-4802-9906-0c4175fcabf7
		summarizeBy: none
		sourceColumn: Column15

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column16
		dataType: string
		isHidden
		lineageTag: e2149550-74b9-4443-8984-d01bfe80c259
		summarizeBy: none
		sourceColumn: Column16

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column17
		dataType: string
		isHidden
		lineageTag: cffa669d-e17a-4325-8093-116a61029d43
		summarizeBy: none
		sourceColumn: Column17

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column18
		dataType: string
		isHidden
		lineageTag: 7c721e4c-17cc-48bb-a09a-661bcb61c134
		summarizeBy: none
		sourceColumn: Column18

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column19
		dataType: string
		isHidden
		lineageTag: 0b3ee7c1-dfd7-4208-aabe-695b8a603be6
		summarizeBy: none
		sourceColumn: Column19

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition '''Результат запроса$''_xlnm#_FilterDatabase' = m
		mode: import
		source =
				let
				    Источник = Excel.Workbook(File.Contents("C:\Users\Slavic Asus\Downloads\query_result_2025-06-24T09_51_41.009478Z.xlsx"), null, true),
				    #"'Результат запроса$'_xlnm#_FilterDatabase1" = Источник{[Name="'Результат запроса$'_xlnm#_FilterDatabase"]}[Data],
				    #"Измененный тип" = Table.TransformColumnTypes(#"'Результат запроса$'_xlnm#_FilterDatabase1",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}})
				in
				    #"Измененный тип"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

